/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author HP
 */
public class Vista extends javax.swing.JFrame {
        

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnArticulo1 = new javax.swing.JButton();
        btnArticulo2 = new javax.swing.JButton();
        btnArticulo3 = new javax.swing.JButton();
        labelVotaciones = new javax.swing.JLabel();
        labelArticulo1 = new javax.swing.JLabel();
        labelArticulo2 = new javax.swing.JLabel();
        labelArticulo3 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnBarraGrafica = new javax.swing.JButton();
        btnPastelGrafica = new javax.swing.JButton();
        btnBitacora = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Votaciones MVC");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnArticulo1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btnArticulo1.setText("Articulo1");
        getContentPane().add(btnArticulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        btnArticulo2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btnArticulo2.setText("Articulo2");
        getContentPane().add(btnArticulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, -1, -1));

        btnArticulo3.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btnArticulo3.setText("Articulo3");
        getContentPane().add(btnArticulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, -1, -1));

        labelVotaciones.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        labelVotaciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelVotaciones.setText("Votaciones");
        getContentPane().add(labelVotaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 230, 40));

        labelArticulo1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        labelArticulo1.setText("0");
        getContentPane().add(labelArticulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        labelArticulo2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        labelArticulo2.setText("0");
        getContentPane().add(labelArticulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, -1, -1));

        labelArticulo3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        labelArticulo3.setText("30");
        getContentPane().add(labelArticulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, -1, -1));

        btnSalir.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 480, -1, -1));

        btnBarraGrafica.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        btnBarraGrafica.setText("Gráfica de Barra");
        btnBarraGrafica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBarraGraficaMouseClicked(evt);
            }
        });
        getContentPane().add(btnBarraGrafica, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, -1, -1));

        btnPastelGrafica.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        btnPastelGrafica.setText("Gráfica de Pastel");
        btnPastelGrafica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPastelGraficaMouseClicked(evt);
            }
        });
        getContentPane().add(btnPastelGrafica, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, -1, -1));

        btnBitacora.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        btnBitacora.setText("Bitacora");
        btnBitacora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBitacoraMouseClicked(evt);
            }
        });
        getContentPane().add(btnBitacora, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 470, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked
  
    private void btnBarraGraficaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBarraGraficaMouseClicked
        int articulo1 = Integer.parseInt(labelArticulo1.getText());
        int articulo2 = Integer.parseInt(labelArticulo2.getText());
        int articulo3 = Integer.parseInt(labelArticulo3.getText());

        DefaultCategoryDataset datos = new DefaultCategoryDataset();

        datos.setValue(articulo1, "Articulos", btnArticulo1.getText());
        datos.setValue(articulo2, "Articulos", btnArticulo2.getText());
        datos.setValue(articulo3, "Articulos", btnArticulo3.getText());

        JFreeChart grafica_barras = ChartFactory.createBarChart3D(
                "Resultados Votaciones", //Nombre del gráfico
                "Articulos", //Nombre de las columnas
                "Votos", //Nombre de la numeración
                datos, //datos del gráfico
                PlotOrientation.VERTICAL, //Orientación
                true, //HAcer la grafica por color 
                true, //herramientas
                false //url del grafico desactivado

        );

        GraficaBarra graficaDeBarra = new GraficaBarra(grafica_barras);
        graficaDeBarra.setVisible(true);
    }//GEN-LAST:event_btnBarraGraficaMouseClicked

   
    private void btnPastelGraficaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPastelGraficaMouseClicked
        int articulo1 = Integer.parseInt(labelArticulo1.getText());
        int articulo2 = Integer.parseInt(labelArticulo2.getText());
        int articulo3 = Integer.parseInt(labelArticulo3.getText());

        DefaultPieDataset datos = new DefaultPieDataset();

        datos.setValue(btnArticulo1.getText(), articulo1);
        datos.setValue(btnArticulo2.getText(), articulo2);
        datos.setValue(btnArticulo3.getText(), articulo3);

        JFreeChart grafico_pastel = ChartFactory.createPieChart(
                "Resultados Votaciones", //Nombre del gráfico
                datos, //datos
                true, //Nombre de las categorias
                true, //herramientas
                false //url del grafico desactivado

        );

        GraficaPastel graficaDePastel = new GraficaPastel(grafico_pastel);
        graficaDePastel.setVisible(true);
    }//GEN-LAST:event_btnPastelGraficaMouseClicked

    private void btnBitacoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBitacoraMouseClicked
        try {
        JOptionPane.showMessageDialog(rootPane, "Se ha generado la Bitacora");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, "Ocurrió un error al generar la Bitácora: " + e.getMessage());
    }
    }//GEN-LAST:event_btnBitacoraMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArticulo1;
    private javax.swing.JButton btnArticulo2;
    private javax.swing.JButton btnArticulo3;
    private javax.swing.JButton btnBarraGrafica;
    private javax.swing.JButton btnBitacora;
    private javax.swing.JButton btnPastelGrafica;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel labelArticulo1;
    private javax.swing.JLabel labelArticulo2;
    private javax.swing.JLabel labelArticulo3;
    private javax.swing.JLabel labelVotaciones;
    // End of variables declaration//GEN-END:variables
}
