/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Vista extends javax.swing.JFrame {
        

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnArticulo1 = new javax.swing.JButton();
        btnArticulo2 = new javax.swing.JButton();
        btnArticulo3 = new javax.swing.JButton();
        labelVotaciones = new javax.swing.JLabel();
        labelResultados = new javax.swing.JLabel();
        labelArticulo1 = new javax.swing.JLabel();
        labelArticulo2 = new javax.swing.JLabel();
        labelArticulo3 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        labelResultado1 = new javax.swing.JLabel();
        labelResultado2 = new javax.swing.JLabel();
        labelResultado3 = new javax.swing.JLabel();
        btnBarraGrafica = new javax.swing.JButton();
        btnPastelGrafica = new javax.swing.JButton();
        btnBitacora = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Votaciones MVC");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnArticulo1.setText("Articulo1");
        getContentPane().add(btnArticulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        btnArticulo2.setText("Articulo2");
        getContentPane().add(btnArticulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        btnArticulo3.setText("Articulo3");
        getContentPane().add(btnArticulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, -1));

        labelVotaciones.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        labelVotaciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelVotaciones.setText("Votaciones");
        getContentPane().add(labelVotaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 180, 40));

        labelResultados.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        labelResultados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelResultados.setText("Resultados");
        getContentPane().add(labelResultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 180, 40));

        labelArticulo1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        labelArticulo1.setText("Articulo1");
        getContentPane().add(labelArticulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, -1, -1));

        labelArticulo2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        labelArticulo2.setText("Articulo2");
        getContentPane().add(labelArticulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, -1, -1));

        labelArticulo3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        labelArticulo3.setText("Articulo3");
        getContentPane().add(labelArticulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, -1, -1));

        btnSalir.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 480, -1, -1));

        labelResultado1.setText("Resultado1");
        getContentPane().add(labelResultado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, -1, -1));

        labelResultado2.setText("Resultado2");
        getContentPane().add(labelResultado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, -1, -1));

        labelResultado3.setText("Resultado3");
        getContentPane().add(labelResultado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, -1, -1));

        btnBarraGrafica.setText("Gráfica de Barra");
        btnBarraGrafica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBarraGraficaMouseClicked(evt);
            }
        });
        getContentPane().add(btnBarraGrafica, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 370, -1, -1));

        btnPastelGrafica.setText("Gráfica de Pastel");
        btnPastelGrafica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPastelGraficaMouseClicked(evt);
            }
        });
        getContentPane().add(btnPastelGrafica, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 420, -1, -1));

        btnBitacora.setText("Bitacora");
        btnBitacora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBitacoraMouseClicked(evt);
            }
        });
        getContentPane().add(btnBitacora, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 480, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    GraficaBarra graficaDeBarra = new GraficaBarra();    
    private void btnBarraGraficaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBarraGraficaMouseClicked
        graficaDeBarra.setVisible(true);
    }//GEN-LAST:event_btnBarraGraficaMouseClicked

    GraficaPastel graficaDePastel = new GraficaPastel();
    private void btnPastelGraficaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPastelGraficaMouseClicked
        graficaDePastel.setVisible(true);
    }//GEN-LAST:event_btnPastelGraficaMouseClicked

    private void btnBitacoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBitacoraMouseClicked
        try {
        JOptionPane.showMessageDialog(rootPane, "Se ha generado la Bitacora");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, "Ocurrió un error al generar la Bitácora: " + e.getMessage());
    }
    }//GEN-LAST:event_btnBitacoraMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArticulo1;
    private javax.swing.JButton btnArticulo2;
    private javax.swing.JButton btnArticulo3;
    private javax.swing.JButton btnBarraGrafica;
    private javax.swing.JButton btnBitacora;
    private javax.swing.JButton btnPastelGrafica;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel labelArticulo1;
    private javax.swing.JLabel labelArticulo2;
    private javax.swing.JLabel labelArticulo3;
    private javax.swing.JLabel labelResultado1;
    private javax.swing.JLabel labelResultado2;
    private javax.swing.JLabel labelResultado3;
    private javax.swing.JLabel labelResultados;
    private javax.swing.JLabel labelVotaciones;
    // End of variables declaration//GEN-END:variables
}
